import { BlogPost } from '@/types/blog.type';

export const dummyBlogPosts: BlogPost[] = [
    {
        id: '1',
        slug: '10-simple-ways-reduce-plastic-waste',
        title: '10 Simple Ways to Reduce Plastic Waste in Your Daily Life',
        excerpt: 'Discover easy, actionable tips to cut down on plastic consumption and make your lifestyle more sustainable.',
        content: 'Full content here...',
        featuredImage: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        category: 'tips',
        author: {
            name: 'Sarah Johnson',
            avatar: null,
            bio: 'Environmental activist and content writer',
        },
        publishedAt: '2024-03-15T10:00:00Z',
        readTime: 5,
        viewCount: 1250,
        tags: ['plastic-free', 'lifestyle', 'tips'],
        isFeatured: true,
    },
    {
        id: '2',
        slug: 'solar-powered-school-transforms-community',
        title: 'How a Solar-Powered School Transformed This Rural Community',
        excerpt: 'The inspiring story of how renewable energy changed education and livelihoods in a remote village.',
        content: 'Full content here...',
        featuredImage: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        category: 'success-stories',
        author: {
            name: 'Michael Chen',
            avatar: null,
            bio: 'Sustainability journalist',
        },
        publishedAt: '2024-03-10T14:30:00Z',
        readTime: 7,
        viewCount: 890,
        tags: ['solar', 'education', 'impact'],
        isFeatured: false,
    },
    {
        id: '3',
        slug: 'vertical-farming-future-urban-agriculture',
        title: 'Vertical Farming: The Future of Urban Agriculture',
        excerpt: 'Exploring how vertical farms are revolutionizing food production in crowded cities.',
        content: 'Full content here...',
        featuredImage: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        category: 'innovations',
        author: {
            name: 'Emma Rodriguez',
            avatar: null,
            bio: 'Agri-tech specialist',
        },
        publishedAt: '2024-03-05T09:15:00Z',
        readTime: 6,
        viewCount: 2340,
        tags: ['farming', 'innovation', 'urban'],
        isFeatured: false,
    },
    {
        id: '4',
        slug: 'green-spark-community-milestone-500-ideas',
        title: 'GreenSpark Reaches 500 Ideas Milestone!',
        excerpt: 'Celebrating our community\'s achievement in sharing 500 sustainability ideas.',
        content: 'Full content here...',
        featuredImage: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        category: 'news',
        author: {
            name: 'David Kim',
            avatar: null,
            bio: 'Community manager',
        },
        publishedAt: '2024-03-01T11:00:00Z',
        readTime: 3,
        viewCount: 567,
        tags: ['announcement', 'milestone'],
        isFeatured: false,
    },
    {
        id: '5',
        slug: 'composting-basics-for-apartment-dwellers',
        title: 'Composting Basics for Apartment Dwellers',
        excerpt: 'You don\'t need a backyard to compost. Learn how to start composting in your apartment.',
        content: 'Full content here...',
        featuredImage: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        category: 'tips',
        author: {
            name: 'Lisa Wang',
            avatar: null,
            bio: 'Zero waste advocate',
        },
        publishedAt: '2024-02-25T08:00:00Z',
        readTime: 4,
        viewCount: 2100,
        tags: ['composting', 'tips', 'apartment'],
        isFeatured: false,
    },
    {
        id: '6',
        slug: 'electric-vehicle-charging-in-rural-areas',
        title: 'Solving EV Charging Challenges in Rural Communities',
        excerpt: 'Innovative solutions bringing electric vehicle infrastructure to underserved rural areas.',
        content: 'Full content here...',
        featuredImage: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        category: 'innovations',
        author: {
            name: 'James Wilson',
            avatar: null,
            bio: 'Clean transportation expert',
        },
        publishedAt: '2024-02-20T14:00:00Z',
        readTime: 8,
        viewCount: 1567,
        tags: ['ev', 'transportation', 'rural'],
        isFeatured: true,
    },
    {
        id: '7',
        slug: 'from-landfill-to-landscape-reclaimed-wood',
        title: 'From Landfill to Landscape: The Reclaimed Wood Movement',
        excerpt: 'How salvaged wood is being transformed into beautiful furniture while reducing waste.',
        content: 'Full content here...',
        featuredImage: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        category: 'success-stories',
        author: {
            name: 'Maria Garcia',
            avatar: null,
            bio: 'Sustainable design writer',
        },
        publishedAt: '2024-02-15T10:30:00Z',
        readTime: 5,
        viewCount: 890,
        tags: ['wood', 'recycling', 'design'],
        isFeatured: false,
    },
    {
        id: '8',
        slug: 'green-rooftops-to-beat-urban-heat',
        title: 'Green Rooftops: A Solution to Urban Heat Islands',
        excerpt: 'How rooftop gardens are cooling our cities and improving air quality.',
        content: 'Full content here...',
        featuredImage: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        category: 'innovations',
        author: {
            name: 'Alex Thompson',
            avatar: null,
            bio: 'Urban planner',
        },
        publishedAt: '2024-02-10T09:00:00Z',
        readTime: 6,
        viewCount: 1100,
        tags: ['rooftop', 'urban', 'cooling'],
        isFeatured: false,
    },
    {
        id: '9',
        slug: 'sustainable-fashion-guide',
        title: 'The Ultimate Guide to Building a Sustainable Wardrobe',
        excerpt: 'Tips for choosing eco-friendly clothing and reducing fashion waste.',
        content: 'Full content here...',
        featuredImage: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        category: 'tips',
        author: {
            name: 'Sophia Lee',
            avatar: null,
            bio: 'Sustainable fashion blogger',
        },
        publishedAt: '2024-02-05T13:00:00Z',
        readTime: 7,
        viewCount: 3450,
        tags: ['fashion', 'clothing', 'tips'],
        isFeatured: false,
    },
];