import { Idea } from '@/types/idea.type';

export const dummyIdeas: Idea[] = [
    {
        id: '1',
        title: 'Solar-Powered Water Purification System',
        problemStatement: 'Clean drinking water is scarce in many rural areas.',
        solution: 'A portable solar-powered water purification device that can filter up to 1000 liters per day.',
        description: 'This innovative system uses solar energy to power UV filtration and reverse osmosis...',
        imageUrl: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        status: 'APPROVED',
        isPaid: false,
        price: null,
        viewCount: 1250,
        voteScore: 342,
        upvotes: 450,
        downvotes: 108,
        commentCount: 45,
        publishedAt: '2024-03-15T10:00:00Z',
        createdAt: '2024-03-10T08:00:00Z',
        updatedAt: '2024-03-15T10:00:00Z',
        author: {
            id: 'user1',
            name: 'Sarah Johnson',
            email: 'sarah@example.com',
            image: null,
        },
        categories: [{ id: '1', name: 'Energy', slug: 'energy' }],
    },
    {
        id: '2',
        title: 'Plastic Waste to Building Bricks',
        problemStatement: 'Plastic pollution is destroying our oceans and environment.',
        solution: 'Converting non-recyclable plastic waste into durable building bricks.',
        description: 'This technology transforms plastic waste into construction materials...',
        imageUrl: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        status: 'APPROVED',
        isPaid: true,
        price: 9.99,
        viewCount: 890,
        voteScore: 567,
        upvotes: 620,
        downvotes: 53,
        commentCount: 89,
        publishedAt: '2024-02-20T14:30:00Z',
        createdAt: '2024-02-15T11:00:00Z',
        updatedAt: '2024-02-20T14:30:00Z',
        author: {
            id: 'user2',
            name: 'Michael Chen',
            email: 'michael@example.com',
            image: null,
        },
        categories: [{ id: '2', name: 'Waste', slug: 'waste' }],
    },
    {
        id: '3',
        title: 'Community Electric Vehicle Sharing',
        problemStatement: 'High cost of EVs and lack of charging infrastructure.',
        solution: 'Community-based EV sharing program with solar charging stations.',
        description: 'A subscription-based electric vehicle sharing system for neighborhoods...',
        imageUrl: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        status: 'APPROVED',
        isPaid: false,
        price: null,
        viewCount: 2340,
        voteScore: 892,
        upvotes: 950,
        downvotes: 58,
        commentCount: 156,
        publishedAt: '2024-01-10T09:00:00Z',
        createdAt: '2024-01-05T13:00:00Z',
        updatedAt: '2024-01-10T09:00:00Z',
        author: {
            id: 'user3',
            name: 'Emma Rodriguez',
            email: 'emma@example.com',
            image: null,
        },
        categories: [{ id: '3', name: 'Transportation', slug: 'transportation' }],
    },
    {
        id: '4',
        title: 'Vertical Farming for Urban Areas',
        problemStatement: 'Food deserts in urban areas with limited farming space.',
        solution: 'Modular vertical farming units for rooftops and vacant buildings.',
        description: 'Hydroponic vertical farming systems that can be installed in any urban space...',
        imageUrl: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        status: 'APPROVED',
        isPaid: false,
        price: null,
        viewCount: 1567,
        voteScore: 678,
        upvotes: 720,
        downvotes: 42,
        commentCount: 67,
        publishedAt: '2024-03-01T11:00:00Z',
        createdAt: '2024-02-25T09:00:00Z',
        updatedAt: '2024-03-01T11:00:00Z',
        author: {
            id: 'user4',
            name: 'David Kim',
            email: 'david@example.com',
            image: null,
        },
        categories: [{ id: '4', name: 'Food', slug: 'food' }],
    },
    {
        id: '5',
        title: 'Rainwater Harvesting System for Apartments',
        problemStatement: 'Water scarcity and high water bills in apartment buildings.',
        solution: 'Compact rainwater collection and filtration system for apartments.',
        description: 'A space-efficient system that collects, filters, and stores rainwater...',
        imageUrl: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        status: 'APPROVED',
        isPaid: true,
        price: 4.99,
        viewCount: 678,
        voteScore: 234,
        upvotes: 290,
        downvotes: 56,
        commentCount: 34,
        publishedAt: '2024-03-20T15:00:00Z',
        createdAt: '2024-03-18T10:00:00Z',
        updatedAt: '2024-03-20T15:00:00Z',
        author: {
            id: 'user1',
            name: 'Sarah Johnson',
            email: 'sarah@example.com',
            image: null,
        },
        categories: [{ id: '5', name: 'Water', slug: 'water' }],
    },
    {
        id: '6',
        title: 'Smart Composting Bin',
        problemStatement: 'Food waste in landfills produces methane gas.',
        solution: 'IoT-enabled composting bin that accelerates decomposition.',
        description: 'A smart bin that monitors temperature, moisture, and aeration...',
        imageUrl: 'https://i.ibb.co.com/C5WkXByf/2.jpg',
        status: 'APPROVED',
        isPaid: false,
        price: null,
        viewCount: 2100,
        voteScore: 745,
        upvotes: 800,
        downvotes: 55,
        commentCount: 98,
        publishedAt: '2024-02-10T10:00:00Z',
        createdAt: '2024-02-01T14:00:00Z',
        updatedAt: '2024-02-10T10:00:00Z',
        author: {
            id: 'user2',
            name: 'Michael Chen',
            email: 'michael@example.com',
            image: null,
        },
        categories: [{ id: '2', name: 'Waste', slug: 'waste' }],
    },
];